tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "inverse-primary": "#005ac2",
                "on-surface-variant": "#c2c6d6",
                "on-background": "#e1e2ec",
                "surface-container-low": "#191b23",
                "surface-container-highest": "#32353c",
                "inverse-surface": "#e1e2ec",
                "on-tertiary-fixed-variant": "#723600",
                "tertiary-fixed-dim": "#ffb786",
                "primary-container": "#4d8eff",
                "on-error-container": "#ffdad6",
                "surface-container-high": "#272a31",
                "surface-container": "#1d2027",
                "on-secondary-fixed-variant": "#39485a",
                "secondary-fixed": "#d4e4fa",
                error: "#ffb4ab",
                "on-tertiary-fixed": "#311400",
                "inverse-on-surface": "#2e3038",
                "secondary-fixed-dim": "#b9c8de",
                "surface-dim": "#10131a",
                "surface-tint": "#adc6ff",
                "tertiary-container": "#df7412",
                "surface-variant": "#32353c",
                "secondary-container": "#39485a",
                surface: "#10131a",
                "surface-bright": "#363941",
                "on-primary-container": "#00285d",
                "on-primary-fixed": "#001a42",
                background: "#10131a",
                "on-surface": "#e1e2ec",
                "on-secondary": "#233143",
                "on-error": "#690005",
                "on-tertiary-container": "#461f00",
                primary: "#adc6ff",
                "on-primary": "#002e6a",
                "surface-container-lowest": "#0b0e15",
                tertiary: "#ffb786",
                "on-tertiary": "#502400",
                "error-container": "#93000a",
                "on-primary-fixed-variant": "#004395",
                "primary-fixed": "#d8e2ff",
                secondary: "#b9c8de",
                "outline-variant": "#424754",
                outline: "#8c909f",
                "on-secondary-container": "#a7b6cc",
                "primary-fixed-dim": "#adc6ff",
                "on-secondary-fixed": "#0d1c2d",
                "tertiary-fixed": "#ffdcc6",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                sm: "8px",
                lg: "24px",
                md: "16px",
                base: "4px",
                xl: "32px",
                gutter: "16px",
                xs: "4px",
                margin: "24px",
            },
            fontFamily: {
                "headline-lg": ["Geist"],
                "label-sm": ["Geist"],
                "body-md": ["Geist"],
                "headline-md": ["Geist"],
                "label-md": ["Geist"],
                "body-lg": ["Geist"],
                "headline-sm": ["Geist"],
            },
            fontSize: {
                "headline-lg": [
                    "30px",
                    {
                        lineHeight: "38px",
                        letterSpacing: "-0.02em",
                        fontWeight: "600",
                    },
                ],
                "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
                "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
                "headline-md": [
                    "24px",
                    {
                        lineHeight: "32px",
                        letterSpacing: "-0.01em",
                        fontWeight: "600",
                    },
                ],
                "label-md": [
                    "12px",
                    {
                        lineHeight: "16px",
                        letterSpacing: "0.02em",
                        fontWeight: "500",
                    },
                ],
                "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "headline-sm": [
                    "20px",
                    { lineHeight: "28px", fontWeight: "600" },
                ],
            },
        },
    },
};